DROP TABLE IF EXISTS songs;

CREATE TABLE songs (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    album VARCHAR(100) NOT NULL,
    duration TEXT NOT NULL,
    year TEXT NOT NULL
);
