services:
  resource-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER}
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  song-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER}
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  service-discovery:
    build: ./service-discovery
    restart: always
    ports:
      - "8761:8761"

  resource-service:
    build: ./resource-service
    depends_on:
      - resource-db
      - service-discovery
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SONG_SERVICE_BASE_URL: ${SONG_SERVICE_BASE_URL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL}
    ports:
      - "8081:8081"

  song-service:
    build: ./song-service
    depends_on:
      - song-db
      - service-discovery
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL}
    deploy:
      replicas: 2
    ports:
      - "8082-8083:8082"
