services:
  postgres-resource:
    image: postgres:latest
    container_name: postgres-resource
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resource_db
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - postgres-resource-data:/var/lib/postgresql/data

  postgres-song:
    image: postgres:latest
    container_name: postgres-song
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: song_db
    ports:
      - "5434:5432"
    networks:
      - backend
    volumes:
      - postgres-song-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  postgres-resource-data:
  postgres-song-data:
