services:
  postgres-resource:
    image: postgres:latest
    container_name: postgres-resource
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resource_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-song:
    image: postgres:latest
    container_name: postgres-song
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: song_db
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  postgres-data:
