spring:
  application:
    name: resource
  datasource:
    url: jdbc:postgresql://localhost:5433/resource-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081

song-service:
  url: http://localhost:8082/api/v1/songs
