spring:
  application:
    name: resource
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resource-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never
  flyway:
    enable: false

server:
  port: 8081

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

song-service:
  base-url: ${SONG_SERVICE_BASE_URL:http://localhost:8082}
  songs-endpoint: /api/v1/songs
